services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        # depends_on:
        #     db:
        #         condition: service_healthy
        env_file:
            - .env
        volumes:
            - ./storage:/var/www/storage
        networks:
            - laravel
        ports:
            - "8000:8000"
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    queue:
        build:
            context: .
            dockerfile: Dockerfile.queue
        container_name: laravel-queue
        restart: unless-stopped
        depends_on:
            app:
                condition: service_healthy
        env_file:
            - .env
        environment:
            - APP_ENV=production
        volumes:
            - ./storage:/var/www/storage
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "pgrep", "-f", "php artisan queue:work"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile.cron
        container_name: laravel-scheduler
        restart: unless-stopped
        depends_on:
            app:
                condition: service_healthy
        env_file:
            - .env
        environment:
            - APP_ENV=production
        volumes:
            - ./storage:/var/www/storage
        networks:
            - laravel
        healthcheck:
            test: ["CMD-SHELL", "ps aux | grep -q 'php.*artisan.*schedule:work'"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    # db:
    #     image: mysql:8.0
    #     container_name: laravel-db
    #     restart: unless-stopped
    #     environment:
    #         - MYSQL_DATABASE=laravel
    #         - MYSQL_USER=laravel
    #         - MYSQL_PASSWORD=secret
    #         - MYSQL_ROOT_PASSWORD=root
    #     volumes:
    #         - db_data:/var/lib/mysql
    #     networks:
    #         - laravel
    #     ports:
    #         - "3306:3306"
    #     healthcheck:
    #         test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    #         start_period: 30s

volumes: {}

networks:
    laravel:
        driver: bridge
