# Ultra-clean Laravel Nixpacks Configuration
# Avoids all Nix conflicts by using minimal configuration

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
CACHE_STORE = "redis"
SESSION_DRIVER = "redis"
QUEUE_CONNECTION = "redis"
BROADCAST_CONNECTION = "reverb"
