# Minimal Nixpacks configuration for Laravel
providers = ["php", "nodejs"]

[variables]
PHP_VERSION = "8.2"
NODE_VERSION = "20"

[build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci --only=production",
    "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
