[variables]
# PHP Configuration
PHP_VERSION = "8.2"
COMPOSER_VERSION = "2"
NODE_VERSION = "20"

# Laravel Configuration
NIXPACKS_BUILD_CMD = "composer install --no-dev --optimize-autoloader && npm ci && npm run build"
NIXPACKS_START_CMD = "supervisord -c /etc/supervisor/conf.d/supervisord.conf"

[phases.setup]
dependsOn = ["install"]

[phases.install]
dependsOn = []

[phases.build]
dependsOn = ["install"]

providers = ["php", "node"]


[apt]
# System packages needed for Laravel, Reverb, Horizon, and database connections
packages = [
    "supervisor",
    "nginx",
    "curl",
    "zip",
    "unzip",
    "git",
    "libpng-dev",
    "libjpeg-dev",
    "libfreetype6-dev",
    "libzip-dev",
    "libicu-dev",
    "libonig-dev",
    "libxml2-dev",
    "libpq-dev",
    "redis-tools",
    "libssl-dev",
    "pkg-config",
    "libsasl2-dev"
]

[env]
# Application Environment
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "error"

# Cache and Session
CACHE_STORE = "redis"
SESSION_DRIVER = "redis"

# Queue Configuration
QUEUE_CONNECTION = "redis"

# Broadcasting
BROADCAST_CONNECTION = "reverb"

# Reverb Configuration
REVERB_SERVER_HOST = "0.0.0.0"
REVERB_SERVER_PORT = "8080"

# PHP Configuration
PHP_MEMORY_LIMIT = "256M"
PHP_MAX_EXECUTION_TIME = "300"
PHP_UPLOAD_MAX_FILESIZE = "64M"
PHP_POST_MAX_SIZE = "64M"

# Composer Configuration
COMPOSER_ALLOW_SUPERUSER = "1"
COMPOSER_NO_INTERACTION = "1"

[start]
cmd = "supervisord -c /etc/supervisor/conf.d/supervisord.conf"

[build]
# Custom build commands for Laravel with all services
cmds = [
    "pecl install mongodb",
    "echo 'extension=mongodb.so' >> /usr/local/etc/php/php.ini",
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci --only=production",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "mkdir -p /etc/supervisor/conf.d",
    "echo '[supervisord]' > /etc/supervisor/conf.d/supervisord.conf",
    "echo 'nodaemon=true' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'user=root' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo '' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo '[program:php-fpm]' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'command=php artisan serve --host=0.0.0.0 --port=80' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'autostart=true' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'autorestart=true' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'user=www-data' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo '' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo '[program:laravel-reverb]' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'command=php artisan reverb:start --host=0.0.0.0 --port=8080' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'directory=/app' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'autostart=true' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'autorestart=true' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'user=www-data' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo '' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo '[program:laravel-horizon]' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'command=php artisan horizon' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'directory=/app' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'autostart=true' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'autorestart=true' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'user=www-data' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo '' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo '[program:laravel-queue-worker]' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'command=php artisan queue:work --sleep=3 --tries=3' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'directory=/app' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'autostart=true' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'autorestart=true' >> /etc/supervisor/conf.d/supervisord.conf",
    "echo 'user=www-data' >> /etc/supervisor/conf.d/supervisord.conf"
]
