[variables]
# PHP Configuration
PHP_VERSION = "8.2"
COMPOSER_VERSION = "2"
NODE_VERSION = "20"

# Laravel Configuration - Simplified for Nixpacks
NIXPACKS_BUILD_CMD = "composer install --no-dev --optimize-autoloader && npm ci && npm run build"
NIXPACKS_START_CMD = "php artisan serve --host=0.0.0.0 --port=8080"

[phases.setup]
dependsOn = ["install"]

[phases.install]
dependsOn = []

[phases.build]
dependsOn = ["install"]

providers = ["php", "nodejs"]

[buildpacks]
# Use custom buildpack for Laravel with Reverb and Horizon
php = "ghcr.io/paketo-buildpacks/php:latest"
nodejs = "ghcr.io/paketo-buildpacks/nodejs:latest"

[apt]
# Essential packages for Laravel
packages = [
    "curl",
    "zip",
    "unzip",
    "git"
]

[env]
# Application Environment
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "error"

# Cache and Session
CACHE_STORE = "redis"
SESSION_DRIVER = "redis"

# Queue Configuration
QUEUE_CONNECTION = "redis"

# Broadcasting
BROADCAST_CONNECTION = "reverb"

# Reverb Configuration
REVERB_SERVER_HOST = "0.0.0.0"
REVERB_SERVER_PORT = "8080"

# PHP Configuration
PHP_MEMORY_LIMIT = "256M"
PHP_MAX_EXECUTION_TIME = "300"
PHP_UPLOAD_MAX_FILESIZE = "64M"
PHP_POST_MAX_SIZE = "64M"

# Composer Configuration
COMPOSER_ALLOW_SUPERUSER = "1"
COMPOSER_NO_INTERACTION = "1"

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"

[build]
# Simplified build commands for Laravel
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci --only=production",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]
